--MjereProizvoda
USE WEBSHOPDB
INSERT INTO MjereProizvoda VALUES ('l')
INSERT INTO MjereProizvoda VALUES ('g')
INSERT INTO MjereProizvoda VALUES ('ml')
INSERT INTO MjereProizvoda VALUES ('kom')
INSERT INTO MjereProizvoda VALUES ('kg')
INSERT INTO MjereProizvoda VALUES ('dag')
--Proizvodi
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('ŠLJIVA',								12.00,		0,	6)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('BRESKVA VINOGRADSKA',				16.00,		0,	6)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('SOK OD RAJÈICE 1L',					23.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('SOK OD MRKVE I JABUKE',				19.00,		0,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('DŽEM OD DUNJA 230G',					19.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('AJVAR 300G',							24.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('GRAH S POVRÆEM',						24.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('PASTA ZA ZUBE POTPUNA ZAŠTITA',		25.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('AGAVA SIRUP BIO 370ML',				49.50,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('CHIA SJEMENKE CRNE 250G',			42.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('ACAI PRAH BIO 60G',					114.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('ALFA ALFA PRAH BIO 250G',			84.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('CHAGA GLJIVE PRAH BIO 125G',			171.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('CHLORELLA BOBICE BIO 250G',			99.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('KOKOSOVO ULJE BIO',					118.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('GOJI BOBICE BIO 250G',				139.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('GURANA PRAH BIO 125G',				137.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('MORINGA PRAH 250G',					133.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('SIBIRSKI GINSENG PRAH BIO 250G',		168.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('SPIRULINA PRAH BIO 250G',			136.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('NONI BIO SOK 330ML',					73.00,		0,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('SPIRULINA BIO 150 PASTIA',			75.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('BLITVA',								16.00,		1,	6)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('CIKLA',								16.00,		1,	6)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('ÈEŠNJAK',							60.00,		1,	6)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('SALATA',								18.00,		1,	6)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('CHERRY RAJÈICE',						32.00,		0,	6)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('SLANUTKOVO BRAŠNO 500g',				36.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('RIŽINO BRAŠNO 500g',					29.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('GRIZ OD PIRA 500g',					24.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('BRAŠNO OD PIRA 500g',				24.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('BRAŠNO PŠENIÈNO INTEGRALNO',			17.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('BRAŠNO RAŽENO',						20.50,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('ZOBENO BRAŠNO',						47.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('SOJINO BRAŠNO', 						17.50,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('SEITAN SVJEŽI',						90.50,		0,	6)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('SEITAN DIMLJENI',					117.20,		0,	6)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('SEITAN POHANI',						112.00,		0,	6)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('TOFU SVJEŽI',						88.00,		1,	6)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('TOFU DIMLJENI',						117.00,		1,	6)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('TOFU POHANI',						112.00,		1,	6)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('ŠTAPIÆI SEIT. I TOF. SA ROŠTILJA',	127.50,		0,	6)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('VEGETARIJANSKI POPEÈCI',				75.00,		1,	6)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('VEGE ZAGREBAÈKI',					123.90,		1,	6)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('EVA Fontaine 7L PLC filter',			1450.00,	1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('EVA Fontaine 12L PLC filter',		1550.00,	1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('EVA Fontaine 25L PLC filter',		2470.00,	1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('EVA Ultimate napredna tuš glava',	760.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('Eva miVoda boca za alkalnu vodu',	490.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('SCHWARZWALD TORTA',					300.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('Staklena boca 0,5l',					99.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('Djeèji set iz tri djela bio',		59.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('Djeèje žlice iz bioplastika 2 kom',	20.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('Žlice za sok iz bioplastike 2 kom',	25.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('Zdjelice za puding iz bioplastike',	30.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('Zdjela 2l iz bioplastike',			60.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('Zdjela 1l iz bioplastike',			45.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('Šalica iz bioplastike 2,5dl',		25.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('Set za salatu iz bioplastike',		35.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('BATAT',								26.00,		1,	6)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('DASKICA ZA REZANJE BIO velika',		72.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('CJEDILJKA IZ BIOPLASTIKE mala',		20.00,		1,	5)
INSERT INTO Proizvodi (Naziv, Cijena, Dostupan, MjereProizvodaId) VALUES ('CJEDILJKA IZ BIOPLASTIKE velika',	25.00,		1,	5)



--Kategorije
INSERT INTO Kategorije VALUES('Bio plastika',	'Bio plastika')
INSERT INTO Kategorije VALUES(	'Brašna',	'Brašna')
INSERT INTO Kategorije VALUES(	'EVA filteri',	'EVA filteri')
INSERT INTO Kategorije VALUES(	'Kozmetika',	'Kozmetika')
INSERT INTO Kategorije VALUES(	'Musli',	'Musli')
INSERT INTO Kategorije VALUES(	'Namazi',	'Namazi')
INSERT INTO Kategorije VALUES(	'Raw Food',	'Raw Food')
INSERT INTO Kategorije VALUES('Sokovi',	'Sokovi')
INSERT INTO Kategorije VALUES('SuperFood',	'SuperFood')
INSERT INTO Kategorije VALUES(	'Vege Program',	'Vege Program')
INSERT INTO Kategorije VALUES(	'Voæe i Povræe',	'Voæe i Povræe')
INSERT INTO Kategorije VALUES(	'Preraðevine',	'Preraðevine')
INSERT INTO Kategorije VALUES(	'Liquid sun',	'Liquid sun')
INSERT INTO Kategorije VALUES(	'Tjestenina',	'Tjestenina')
INSERT INTO Kategorije VALUES(	'Med eko',	'Med eko')

--Kategorije proizvodi
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))
INSERT INTO KategorijeProizvodi VALUES((SELECT TOP 1 Id FROM Proizvodi ORDER BY NEWID()), (SELECT TOP 1 Id FROM Kategorije ORDER BY NEWID()))



-- Korisnici
INSERT INTO Korisnici VALUES('Mirko', 'Spirko', 'mirko@spirko.hr', 'Spirkov put 24 bb', '01/220-132', 'Ima pitbull-a koji grize.')
INSERT INTO Korisnici VALUES('Jura', 'Klafura', 'jura@klafura.hr', 'Uzaludna cesta 12', '091/507-8100', 'Naruèuje, a nema novaca za platiti.')


