-- SET LANGUAGE 'Hrvatski'

-- DATEADD
SELECT DATEADD(DAY, 3, GETDATE())

-- DATEDIFF
SELECT DATEDIFF(DAY, '2025-11-1', GETDATE())
SELECT DATEDIFF(DAY, DATEADD(DAY, -3, GETDATE()), GETDATE()) AS 'Broj dana'

-- DATENAME
SELECT DATENAME(MONTH, '2025-11-21')
SELECT DATENAME (DAY, GETDATE())

--DATEPART
SELECT DATEPART(MONTH, '2025-11-21')
SELECT DATEPART(DAY, '2025-11-21')
SELECT DATEPART(YEAR, '2025-11-21')

--CAST
SELECT GETDATE()
SELECT CAST(GETDATE() AS NVARCHAR)

--CONVERT
SELECT CONVERT(nvarchar, GETDATE(), 104)