CREATE DATABASE WEBSHOPDB
USE WEBSHOPDB

CREATE TABLE Kategorije (
Id INT PRIMARY KEY IDENTITY (1,1),
Naziv NVARCHAR(50) NOT NULL,
Opis NVARCHAR(500)
);
GO

CREATE TABLE MjereProizvoda(
Id INT PRIMARY KEY IDENTITY(1,1),
Naziv NVARCHAR(50) NOT NULL
);
go

CREATE TABLE Korisnici(
Id INT PRIMARY KEY IDENTITY(1,1),
Ime NVARCHAR(50) NOT NULL,
Prezime NVARCHAR(100) NOT NULL,
Email NVARCHAR(150),
AdresaDostave NVARCHAR(250),
Kontakt NVARCHAR(50),
Napomena NVARCHAR(250)
);
GO

CREATE TABLE Proizvodi(
Id INT PRIMARY KEY IDENTITY(1,1),
MjereProizvodaId INT FOREIGN KEY REFERENCES MjereProizvoda(Id),
VrijemeKreiranja DATETIME DEFAULT GETDATE(),
Naziv NVARCHAR(100) NOT NULL,
Cijena DECIMAL(20,2) NOT NULL,
Dostupan BIT nOT NULL,
);
GO

CREATE TABLE KategorijeProizvodi(
Id INT PRIMARY KEY IDENTITY(1,1),
Proizvod INT FOREIGN KEY REFERENCES Proizvodi(Id),
KategorijaId INT FOREIGN KEY REFERENCES Kategorije(Id)
);
GO

CREATE TABLE Narudzbe(
Id INT PRIMARY KEY IDENTITY(1,1),
KorisnikId INT FOREIGN KEY REFERENCES Korisnici(Id),
DatumKreiranja DATETIME DEFAULT GETDATE(),
DatumVrijemeDostave DATETIME,
JeDostavljeno BIT
);
GO

CREATE TABLE NarudzbeDetalji(
Id INT PRIMARY KEY IDENTITY(1,1),
NarudzbaId INT FOREIGN KEY REFERENCES Narudzbe(Id),
ProizvodId INT FOREIGN KEY REFERENCES Proizvodi(Id),
Kolicina INT NOT NULL,
JedCijena DECIMAL(20,2) NOT NULL
);
GO